version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loki?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: loki
      SPRING_DATASOURCE_PASSWORD: loki@123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: loki@123
      MYSQL_DATABASE: loki
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
